In [7]:
import numpy as np 
import pandas as pd 
import math
# I want to simulate the algorithm I want to implement in systemverilog.

# I want to load a list of x numbers in a 1D array, similar to how i would load weights into a mem file
weight_rows = 4
weight_cols = 6
num_weights = weight_rows * weight_cols
sys_arr_dim = 3

tile_rows = math.ceil(weight_rows / sys_arr_dim)
tile_cols = math.ceil(weight_cols / sys_arr_dim)


weights_1d = np.random.randint(num_weights, size=num_weights)
weights_matrix = weights_1d.reshape(weight_rows, weight_cols)
print("Weights Matrix:")
print(weights_matrix)

print("1D Weights:")
print(weights_1d)

# I want to tile the weights into 3x3 tiles, similar to how i would tile weights for a systolic array
# Read in Top Left Quadrant, Top Right Quadrant, Bottom Left Quadrant, Bottom Right Quadrant
tiled_weights = []
tile_row_ctr = 0
tile_col_ctr = 0
while(tile_row_ctr < tile_rows):
    tile_col_ctr = 0
    while (tile_col_ctr < tile_cols): # Making sure we don't tile more than needed
        mat_row_ctr = tile_row_ctr * sys_arr_dim # mat_row_ctr is the row index in the original weight matrix
        while(mat_row_ctr < (tile_row_ctr * sys_arr_dim) + sys_arr_dim): # Making sure we don't read more than needed
            # while(tile_col_ctr < tile_cols):
            # mat_col_ctr = tile_col_ctr * weight_cols # mat_col_ctr is the column index in the 
            mat_col_ctr = tile_col_ctr * sys_arr_dim
            while(mat_col_ctr < (tile_col_ctr * sys_arr_dim) + sys_arr_dim):
                addrs = mat_row_ctr * weight_cols + mat_col_ctr
                if(addrs > num_weights - 1): # Making sure we don't read out of bounds
                    tiled_weights.append(0) # Pad with 0 if we read out of bounds
                else:
                    tiled_weights.append(weights_1d[addrs]) # Load One Weight at a time from the 1D array
                mat_col_ctr += 1
            mat_row_ctr += 1
        tile_col_ctr += 1
        print("Tiled Weights:")
        print(np.array(tiled_weights).reshape(sys_arr_dim, sys_arr_dim)) # Print the tiled weights in a 3x3 format
        tiled_weights = [] # Clear the tiled weights for the next tile
    tile_row_ctr += 1



Weights Matrix:
[[ 6 16 20 13 10 17]
 [21 16 20  3  9 18]
 [ 3 16 13 23  1  6]
 [ 3 15  0 21 16 21]]
1D Weights:
[ 6 16 20 13 10 17 21 16 20  3  9 18  3 16 13 23  1  6  3 15  0 21 16 21]
Tiled Weights:
[[ 6 16 20]
 [21 16 20]
 [ 3 16 13]]
Tiled Weights:
[[13 10 17]
 [ 3  9 18]
 [23  1  6]]
Tiled Weights:
[[ 3 15  0]
 [ 0  0  0]
 [ 0  0  0]]
Tiled Weights:
[[21 16 21]
 [ 0  0  0]
 [ 0  0  0]]
